# Generated by Django 3.0.5 on 2020-05-06 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_manager', '0002_todoitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(default='not done', max_length=20),
        ),
        migrations.CreateModel(
            name='TodoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='todoitem',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_manager.TodoTable'),
        ),
    ]
