# Generated by Django 3.0.5 on 2020-05-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0003_auto_20200506_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='status',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='выполнено'),
        ),
    ]
