# Generated by Django 3.0.5 on 2020-05-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0006_auto_20200520_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks_manager.TodoTable'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-slug'], name='tasks_manag_slug_0e8f42_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['-created'], name='tasks_manag_created_2ae5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='todotable',
            index=models.Index(fields=['-created'], name='tasks_manag_created_b5560f_idx'),
        ),
    ]
