# Generated by Django 3.0.5 on 2020-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user_avatars/default.png', upload_to='user_avatars/%Y/%m/%d'),
        ),
    ]
